services:
  nginx-proxy:
    image: nginx:latest
    container_name: nginx-proxy
    volumes:
      - type: bind
        source: nginx-proxy.conf
        target: /etc/nginx/nginx.conf
    expose:
      - 80
    network_mode: host

  nginx-web:
    image: nginx:latest
    container_name: nginx-web
    ports:
      - 8080:80
    volumes:
      - type: bind
        source: nginx-web.conf
        target: /etc/nginx/nginx.conf
    networks:
      - custom-network

  app:
    tty: true
    container_name: app
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - type: bind
        source: .
        target: /app
    networks:
      - custom-network

networks:
  custom-network:
    driver: bridge
