services:
  app:
    tty: true
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    ports:
      - 3000:3000
    volumes:
      - type: bind 
        source: ~/.ssh
        target: /home/node/.ssh
      - type: bind
        source: .
        target: /app
  web:
    image: nginx:latest
    ports:
      - 80
    volumes:
      - type: bind
        source: nginx.conf
        target: /etc/nginx/nginx.conf
